<?php

return [


    'api' => [
        [
            'module' => 'content',
            'section' => 'api',
            'package' => 'main',
            'handler' => 'main',
            'permission' => 'api-content-main',
            'role' => [
                'member',
                'admin',
                'dafi',
                'club',
                'affiliate',
                'b2b',
                'luxirana',
            ],
        ],
        [

            'module' => 'content',
            'section' => 'api',
            'package' => 'item',
            'handler' => 'list',
            'permissions' => 'api-item-list',
            'role' => [
                'member',
                'admin',
                'dafi',
                'club',
                'affiliate',
                'b2b',
                'luxirana',
            ],
        ],


        [
            'module' => 'content',
            'section' => 'api',
            'package' => 'cart',
            'handler' => 'add',
            'permission' => 'api-content-cart-add',
            'role' => [
                'member',
                'admin',
                'dafi',
                'club',
                'affiliate',
                'b2b',
                'luxirana',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'api',
            'package' => 'cart',
            'handler' => 'update',
            'permission' => 'api-content-cart-update',
            'role' => [
                'member',
                'admin',
                'dafi',
                'club',
                'affiliate',
                'b2b',
                'luxirana',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'api',
            'package' => 'cart',
            'handler' => 'delete',
            'permission' => 'api-content-cart-delete',
            'role' => [
                'member',
                'admin',
                'dafi',
                'club',
                'affiliate',
                'b2b',
                'luxirana',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'api',
            'package' => 'cart',
            'handler' => 'list',
            'permission' => 'api-content-cart-list',
            'role' => [
                'member',
                'admin',
                'dafi',
                'club',
                'affiliate',
                'b2b',
                'luxirana',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'api',
            'package' => 'order',
            'handler' => 'add',
            'permission' => 'api-content-order-add',
            'role' => [
                'member',
                'admin',
                'dafi',
                'club',
                'affiliate',
                'b2b',
                'luxirana',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'api',
            'package' => 'order',
            'handler' => 'list',
            'permission' => 'api-content-order-list',
            'role' => [
                'member',
                'admin',
                'dafi',
                'club',
                'affiliate',
                'b2b',
                'luxirana',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'api',
            'package' => 'address',
            'handler' => 'add',
            'permission' => 'api-content-address-add',
            'role' => [
                'member',
                'admin',
                'dafi',
                'club',
                'affiliate',
                'b2b',
                'luxirana',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'api',
            'package' => 'address',
            'handler' => 'list',
            'permission' => 'api-content-address-list',
            'role' => [
                'member',
                'admin',
                'dafi',
                'club',
                'affiliate',
                'b2b',
                'luxirana',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'api',
            'package' => 'question',
            'handler' => 'add',
            'permission' => 'api-content-question-add',
            'role' => [
                'member',
                'admin',
                'dafi',
                'club',
                'affiliate',
                'b2b',
                'luxirana',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'api',
            'package' => 'question',
            'handler' => 'reply',
            'permission' => 'api-content-question-reply',
            'role' => [
                'member',
                'admin',
                'dafi',
                'club',
                'affiliate',
                'b2b',
                'luxirana',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'api',
            'package' => 'question',
            'handler' => 'get',
            'permission' => 'api-content-question-get',
            'role' => [
                'member',
                'admin',
                'dafi',
                'club',
                'affiliate',
                'b2b',
                'luxirana',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'api',
            'package' => 'support',
            'handler' => 'add',
            'permission' => 'api-content-support-add',
            'role' => [
                'member',
                'admin',
                'dafi',
                'club',
                'affiliate',
                'b2b',
                'luxirana',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'api',
            'package' => 'support',
            'handler' => 'reply',
            'permission' => 'api-content-support-reply',
            'role' => [
                'member',
                'admin',
                'dafi',
                'club',
                'affiliate',
                'b2b',
                'luxirana',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'api',
            'package' => 'support',
            'handler' => 'list',
            'permission' => 'api-content-support-list',
            'role' => [
                'member',
                'admin',
                'dafi',
                'club',
                'affiliate',
                'b2b',
                'luxirana',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'api',
            'package' => 'support',
            'handler' => 'get',
            'permission' => 'api-content-support-get',
            'role' => [
                'member',
                'admin',
                'dafi',
                'club',
                'affiliate',
                'b2b',
                'luxirana',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'api',
            'package' => 'location',
            'handler' => 'list',
            'permission' => 'api-content-location-list',
            'role' => [
                'member',
                'admin',
                'dafi',
                'club',
                'affiliate',
                'b2b',
                'luxirana',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'api',
            'package' => 'location',
            'handler' => 'get',
            'permission' => 'api-content-location-get',
            'role' => [
                'member',
                'admin',
                'dafi',
                'club',
                'affiliate',
                'b2b',
                'luxirana',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'api',
            'package' => 'category',
            'handler' => 'list',
            'permission' => 'api-content-category-list',
            'role' => [
                'member',
                'admin',
                'dafi',
                'club',
                'affiliate',
                'b2b',
                'luxirana',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'api',
            'package' => 'setting',
            'handler' => 'version',
            'permission' => 'api-content-setting-version',
            'role' => [
                'member',
                'admin',
                'dafi',
                'club',
                'affiliate',
                'b2b',
                'luxirana',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'api',
            'package' => 'reserve',
            'handler' => 'add',
            'permission' => 'api-content-reserve-add',
            'role' => [
                'member',
                'admin',
                'dafi',
                'club',
                'affiliate',
                'b2b',
                'luxirana',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'api',
            'package' => 'reserve',
            'handler' => 'remove',
            'permission' => 'api-content-reserve-remove',
            'role' => [
                'member',
                'admin',
                'dafi',
                'club',
                'affiliate',
                'b2b',
                'luxirana',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'api',
            'package' => 'reserve',
            'handler' => 'list',
            'permission' => 'api-content-reserve-list',
            'role' => [
                'member',
                'admin',
                'dafi',
                'club',
                'affiliate',
                'b2b',
                'luxirana',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'api',
            'package' => 'opinion',
            'handler' => 'like',
            'permission' => 'api-content-opinion-like',
            'role' => [
                'member',
                'admin',
                'dafi',
                'club',
                'affiliate',
                'b2b',
                'luxirana',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'api',
            'package' => 'opinion',
            'handler' => 'dislike',
            'permission' => 'api-content-opinion-dislike',
            'role' => [
                'member',
                'admin',
                'dafi',
                'club',
                'affiliate',
                'b2b',
                'luxirana',
            ],
        ],

    ],

    'admin' => [
        [
            'module' => 'content',
            'section' => 'admin',
            'package' => 'item',
            'handler' => 'list',
            'permissions' => 'item-list',
            'role' => [
                'admin',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'admin',
            'package' => 'item',
            'handler' => 'detail',
            'permissions' => 'item-detail',
            'role' => [
                'admin',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'admin',
            'package' => 'item',
            'handler' => 'add',
            'permissions' => 'item-add',
            'role' => [
                'admin',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'admin',
            'package' => 'item',
            'handler' => 'edit',
            'permissions' => 'item-edit',
            'role' => [
                'admin',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'admin',
            'package' => 'item',
            'handler' => 'delete',
            'permissions' => 'item-delete',
            'role' => [
                'admin',
            ],
        ],

        [
            'module' => 'content',
            'section' => 'admin',
            'package' => 'support',
            'handler' => 'add',
            'permission' => 'admin-content-support-add',
            'role' => [
                'admin',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'admin',
            'package' => 'support',
            'handler' => 'reply',
            'permission' => 'admin-content-support-reply',
            'role' => [
                'admin',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'admin',
            'package' => 'support',
            'handler' => 'list',
            'permission' => 'admin-content-support-list',
            'role' => [
                'admin',
            ],
        ],
        [
            'module' => 'content',
            'section' => 'admin',
            'package' => 'support',
            'handler' => 'get',
            'permission' => 'admin-content-support-get',
            'role' => [
                'admin',
            ],
        ],
    ],

];